/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import javax.swing.JOptionPane;

/**
 *
 * @author JMagoSV
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btnEjerc1 = new javax.swing.JMenu();
        btnEjerc2 = new javax.swing.JMenu();
        btnEjerc7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guía de Ejercicios 2 ::: Mauricio González");

        btnEjerc1.setText("Ejercicio 1");
        btnEjerc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjerc1MouseClicked(evt);
            }
        });
        btnEjerc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjerc1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(btnEjerc1);

        btnEjerc2.setText("Ejercicio 2");
        btnEjerc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjerc2MouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEjerc2);

        btnEjerc7.setText("Ejercicio 7");
        btnEjerc7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjerc7MouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEjerc7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjerc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjerc1ActionPerformed
        try
        {
            FrmEjerc1 obje = new FrmEjerc1();
            obje.setVisible(true);
        }
        catch (Exception e)
        {
            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, e.getMessage());
//            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEjerc1ActionPerformed

    private void btnEjerc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjerc1MouseClicked
        try
        {
            FrmEjerc1 obje = new FrmEjerc1();
            obje.setVisible(true);
        }
        catch (Exception e)
        {
            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, e.getMessage());
//            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEjerc1MouseClicked

    private void btnEjerc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjerc2MouseClicked
        FrmEjerc2 obje = new FrmEjerc2();
        obje.setVisible(true);
    }//GEN-LAST:event_btnEjerc2MouseClicked

    private void btnEjerc7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjerc7MouseClicked
        FrmEjerc7 obje = new FrmEjerc7();
        obje.setVisible(true);
    }//GEN-LAST:event_btnEjerc7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnEjerc1;
    private javax.swing.JMenu btnEjerc2;
    private javax.swing.JMenu btnEjerc7;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
